epoch: 250
samp_len: 64600
batch_size: 32
optimizer: Adam
lr: 0.001
warmup: 10000

#dataset-related
data:
  num_method: 6
  k_fold: 3


model:
  drop_out: 0.1
  samp_len: 64600

  num_filter: 128  # no. of filter for SincNet
  filt_len: 80
  in_channels: 1
  max_pool_len: 3

  patch_size: 24
  patch_embed: 256
  seq_size: [1024,256,128]
  
  encoder_hidden: 1024
  num_block: 6
  num_head: 4

  #For encoder-decoder
  encoder_channel: [64, 128, 256, 256]
  kernel: 3
  stride: 2
  padding: 1

  gru_hidden: 512
  gru_layer: 1

  mlp_size: [296, 256]
  nb_classes: 2
